version: '3.7'
services:
  nest-api:
    image: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    depends_on:
      - postgres
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    networks:
      - postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:  
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
    postgres:
      driver: bridge
